"""Create models migrations

Revision ID: 97524acb59e9
Revises: 9e8edb0a1c31
Create Date: 2023-09-03 14:13:43.933386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97524acb59e9'
down_revision = '9e8edb0a1c31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('last_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'last_name')
    # ### end Alembic commands ###
