"""Change restaurant price property from string to intager

Revision ID: a2ae993894ad
Revises: 97524acb59e9
Create Date: 2023-09-03 17:10:15.907738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2ae993894ad'
down_revision = '97524acb59e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
